# Generated by Django 4.2.16 on 2024-10-27 08:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temple_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temple_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'permissions': [('can_add_bill', 'Can add bill'), ('can_change_bill', 'Can change bill'), ('can_delete_bill', 'Can delete bill'), ('can_view_bill', 'Can view bill')],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_manager.bill')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temple_inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(through='billing_manager.BillItem', to='temple_inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bill',
            name='temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temple_auth.temple', verbose_name='Temple'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
