# Generated by Django 4.2.16 on 2024-10-27 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=500)),
                ('temple_place', models.CharField(blank=True, max_length=120, null=True)),
                ('temple_bill_title', models.CharField(blank=True, max_length=300, null=True)),
                ('temple_bill_mid', models.CharField(blank=True, max_length=400, null=True)),
                ('temple_bill_footer', models.CharField(blank=True, max_length=320, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved_by_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('temples', models.ManyToManyField(blank=True, to='temple_auth.temple')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
